// src/actionTypes.js

// User Authentication
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_ERROR = 'USER_SIGNUP_ERROR';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';

// Admin Authentication
export const ADMIN_SIGNUP_SUCCESS = 'ADMIN_SIGNUP_SUCCESS';
export const ADMIN_SIGNUP_ERROR = 'ADMIN_SIGNUP_ERROR';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_ERROR = 'ADMIN_LOGIN_ERROR';

// Course Management
export const COURSE_CREATE_SUCCESS = 'COURSE_CREATE_SUCCESS';
export const COURSE_CREATE_ERROR = 'COURSE_CREATE_ERROR';
export const COURSE_UPDATE_SUCCESS = 'COURSE_UPDATE_SUCCESS';
export const COURSE_UPDATE_ERROR = 'COURSE_UPDATE_ERROR';
export const COURSE_DELETE_SUCCESS = 'COURSE_DELETE_SUCCESS';
export const COURSE_DELETE_ERROR = 'COURSE_DELETE_ERROR';

// Class Management
export const CLASS_CREATE_SUCCESS = 'CLASS_CREATE_SUCCESS';
export const CLASS_CREATE_ERROR = 'CLASS_CREATE_ERROR';
export const CLASS_UPDATE_SUCCESS = 'CLASS_UPDATE_SUCCESS';
export const CLASS_UPDATE_ERROR = 'CLASS_UPDATE_ERROR';
export const CLASS_DELETE_SUCCESS = 'CLASS_DELETE_SUCCESS';
export const CLASS_DELETE_ERROR = 'CLASS_DELETE_ERROR';

// Fetching Classes
export const FETCH_CLASSES_SUCCESS = 'FETCH_CLASSES_SUCCESS';
export const FETCH_CLASSES_ERROR = 'FETCH_CLASSES_ERROR';

// Selecting Courses
export const USER_SELECT_COURSES_SUCCESS = 'USER_SELECT_COURSES_SUCCESS';
export const USER_SELECT_COURSES_ERROR = 'USER_SELECT_COURSES_ERROR';

// Submitting Tests
export const USER_SUBMIT_TEST_SUCCESS = 'USER_SUBMIT_TEST_SUCCESS';
export const USER_SUBMIT_TEST_ERROR = 'USER_SUBMIT_TEST_ERROR';

// Fetching User Results
export const FETCH_USER_RESULT_DATA_REQUEST = 'FETCH_USER_RESULT_DATA_REQUEST';
export const FETCH_USER_RESULT_DATA_SUCCESS = 'FETCH_USER_RESULT_DATA_SUCCESS';
export const FETCH_USER_RESULT_DATA_FAILURE = 'FETCH_USER_RESULT_DATA_FAILURE';


//Loading State
export const SET_LOADING  = "SET_LOADING"
export const CLEAR_LOADING = "CLEAR_LOADING"
export const RESET_ERROR = "RESET_ERROR"


